// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxfAnQH-Dg63I3xA1uq5_76elKIwcG7HU',
    appId: '1:431042721422:web:b5a0d640a2bf3c6f82fbdf',
    messagingSenderId: '431042721422',
    projectId: 'flutterapp-ae11f',
    authDomain: 'flutterapp-ae11f.firebaseapp.com',
    storageBucket: 'flutterapp-ae11f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRMDzIGfxw93EFBnAVTcUnqfRFcLP1AwU',
    appId: '1:431042721422:android:23599c33bb635a0b82fbdf',
    messagingSenderId: '431042721422',
    projectId: 'flutterapp-ae11f',
    storageBucket: 'flutterapp-ae11f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlqb4rBmiV7c896rGmRLsXnCryYJzFW4E',
    appId: '1:431042721422:ios:7ddfe34f74165c2982fbdf',
    messagingSenderId: '431042721422',
    projectId: 'flutterapp-ae11f',
    storageBucket: 'flutterapp-ae11f.firebasestorage.app',
    iosBundleId: 'com.example.moblileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlqb4rBmiV7c896rGmRLsXnCryYJzFW4E',
    appId: '1:431042721422:ios:7ddfe34f74165c2982fbdf',
    messagingSenderId: '431042721422',
    projectId: 'flutterapp-ae11f',
    storageBucket: 'flutterapp-ae11f.firebasestorage.app',
    iosBundleId: 'com.example.moblileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxfAnQH-Dg63I3xA1uq5_76elKIwcG7HU',
    appId: '1:431042721422:web:105c6d4b7d8108f082fbdf',
    messagingSenderId: '431042721422',
    projectId: 'flutterapp-ae11f',
    authDomain: 'flutterapp-ae11f.firebaseapp.com',
    storageBucket: 'flutterapp-ae11f.firebasestorage.app',
  );
}
